name: Update oc.user.debuger

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [dispatch-from-oc.user]
jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BASE_IMAGE_RELEASE: [18.04, 20.04, 21.04]
    steps: 
    - name: Clone repository
      run: |
        rm -rf ..?* .[!.]* *
        git clone "https://${{ secrets.USER_NAME }}:${{ secrets.TOKEN }}@github.com/abcdesktopio/oc.user.debuger.git" .

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push oc.user.${{ matrix.BASE_IMAGE_RELEASE }}:debuger
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        build-args: |
          BASE_IMAGE=abcdesktopio/oc.user.${{ matrix.BASE_IMAGE_RELEASE }}:debuger
        tags: |
          abcdesktopio/oc.user.${{ matrix.BASE_IMAGE_RELEASE }}:debuger
