name: Test and update oc.user.18.04.debuger

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [dispatch-from-oc.user.18.04]
jobs:
  main:
    runs-on: self-hosted
    steps: 
    - name: Clone repository
      run: |
        rm -rf ..?* .[!.]* *
        git clone "https://${{ secrets.USER_NAME }}:${{ secrets.TOKEN }}@github.com/abcdesktopio/oc.user.18.04.debuger.git" .

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push oc.user.18.04:debuger
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          abcdesktopio/oc.user.18.04:debuger
